# Generated by Django 5.2 on 2025-04-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookreader', '0003_alter_book_book_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='book_coverimage/'),
        ),
    ]
