# Generated by Django 5.2 on 2025-04-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookreader', '0005_book_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
