# Generated by Django 5.2 on 2025-04-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookreader', '0007_book_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.AddField(
            model_name='book',
            name='content_pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
    ]
